version: '3.9'

services:

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    image: app/python
    container_name: fastapi
    volumes:
      - ./fastapi:/data/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      # `fastapi`Because the service (container) needs to be started first`depends_on`Is specified
      - fastapi
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge